// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocialMediaLists.Persistence.EntityFramework.Common.Database;

namespace SocialMediaLists.Persistence.EntityFramework.Migrations
{
    [DbContext(typeof(SocialMediaListsDbContext))]
    [Migration("20200531201030_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("SocialMediaLists.Domain.People.Person", b =>
                {
                    b.Property<long>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("PersonId");

                    b.ToTable("People");
                });

            modelBuilder.Entity("SocialMediaLists.Domain.People.SocialAccount", b =>
                {
                    b.Property<long>("SocialAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Network")
                        .HasColumnType("TEXT");

                    b.Property<long>("PersonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SocialAccountId");

                    b.HasIndex("PersonId");

                    b.ToTable("SocialAccount");
                });

            modelBuilder.Entity("SocialMediaLists.Domain.SocialLists.SocialList", b =>
                {
                    b.Property<long>("SocialListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("SocialListId");

                    b.ToTable("SocialLists");
                });

            modelBuilder.Entity("SocialMediaLists.Domain.SocialLists.SocialListPerson", b =>
                {
                    b.Property<long>("SocialListId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PersonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SocialListId", "PersonId");

                    b.HasIndex("PersonId");

                    b.ToTable("SocialListPerson");
                });

            modelBuilder.Entity("SocialMediaLists.Domain.People.SocialAccount", b =>
                {
                    b.HasOne("SocialMediaLists.Domain.People.Person", "Person")
                        .WithMany("Accounts")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SocialMediaLists.Domain.SocialLists.SocialListPerson", b =>
                {
                    b.HasOne("SocialMediaLists.Domain.People.Person", "Person")
                        .WithMany("SocialListPerson")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialMediaLists.Domain.SocialLists.SocialList", "SocialList")
                        .WithMany("SocialListPerson")
                        .HasForeignKey("SocialListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
